apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        command: ["cloudflared", "tunnel"]
        args: ["--no-autoupdate", "run", "--token", "$(TOKEN)"]
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: token
