apiVersion: v1
kind: Service
metadata:
  name: esphome
spec:
  selector:
    app: esphome
  ports:
  - name: api
    protocol: TCP
    port: 6052
    targetPort: 6052
  - name: dashboard
    protocol: TCP
    port: 6123
    targetPort: 6123
